# Scans Deliverables folders for .docx files in target folders (DD130, D0180, etc.).
# Converts each .docx to Markdown using the Microsoft MarkItDown library, optionally stripping boilerplate.
# Output is written to OUTPUT_DIR/<project>/<folder-slug>/<filename>.md (creates dirs as needed).
#
# =============================================================================
#  PROCESSING PIPELINE  (per .docx file, in order)
# =============================================================================
#
#  1. FOLDER FILTER — only folders whose name starts with a TARGET_FOLDER_PREFIXES
#     entry are entered; all others are skipped entirely.
#
#  2. DEPRECATION CHECK — if SKIP_DEPRECATED is True and the word "deprecated"
#     appears anywhere in the file path (case-insensitive), the file is skipped
#     and counted under "Skipped" in the summary.
#
#  3. STEM CLEANING (clean_stem) — the filename stem is normalised:
#       • em-dashes and en-dashes are replaced with plain hyphens.
#       • Runs of multiple spaces are collapsed to one.
#       • The folder name prefix is stripped when the filename redundantly
#         repeats it (e.g. "DD130 - Detailed Design - Foo.docx" inside folder
#         "DD130 - Detailed Design" becomes stem "Foo").
#
#  4. GENERIC STEM CHECK — if the cleaned stem is empty or matches the
#     descriptive part of the folder name (adds no specificity), the domain
#     discriminator (the second-level folder, e.g. "AMPLIO PRINT") is
#     prepended immediately to make the output filename unique.
#
#  5. FOLDER SLUG (slugify_folder) — the target folder name is converted to a
#     URL-safe slug used as the output sub-directory name:
#     spaces and " - " separators become dashes.
#
#  6. TWO-PHASE ARCHITECTURE & DUPLICATE DETECTION —
#     Phase 1 (Discovery): Walks directories, detects duplicates, updates paths.
#     Phase 2 (Execution): Concurrently parses docx files via ProcessPoolExecutor.
#       • If a collision is found and both files have a domain discriminator,
#         the already-queued file is renamed to include its discriminator and
#         the new file is queued with its own discriminator prefix.
#       • If no discriminator is available, a numeric counter suffix (-2, -3 …)
#         is appended to the new file's name.
#
#  7. CONVERSION (markitdown) — the .docx is converted to Markdown in parallel.
#
#  8. STATUS EXTRACTION — the document status is read from the metadata table.
#     If the numeric value is below DRAFT_THRESHOLD the document is a draft.
#     Files with a missing or unreadable status field are counted separately.
#
#  9. BOILERPLATE STRIPPING (strip_boilerplate) — if CLEAN_MD is True:
#       • Everything before the References section is removed (cover image,
#         metadata tables, document history).
#       • The Table of Contents block is removed.
#       • The References section and all content after the ToC are kept.
#       • Uses robust regex to identify multi-language headers regardless of MD formatting.
#
# 10. TABLE HEADER FIX (fix_table_empty_header_rows) — if CLEAN_MD is True:
#     Word sometimes emits an all-empty row before the separator row in tables,
#     which breaks Markdown rendering. The rows are reordered to produce valid
#     Markdown tables.
#
# 11. IMAGE EXTRACTION (extract_images) — Base64 Data URIs generated by markitdown
#     are hashed (MD5) and matched against the original media binaries extracted
#     directly from the DOCX ZIP structure (Content-Addressable Storage).
#     Images are saved to .attachments/ and references are patched.
#     Transcoded images missing from ZIP are dumped directly from Base64 fallback.
#
# 12. WRITE — the final .md is written to:
#     OUTPUT_DIR/<project>/<folder-slug>/<stem>.md
#     Skipped in DRY_RUN; the path is still reported.
#
# 13. DRAFT RENAME — if the document status is below DRAFT_THRESHOLD, the
#     output file is renamed to draft-<stem>.md after writing.
#
# =============================================================================

import argparse
import dataclasses
import os
import re
import zipfile
import sys
import time
import hashlib
import base64
import mimetypes
import concurrent.futures
import json

# MICROSOFT library (https://github.com/microsoft/markitdown)
import markitdown

# =============================================================================
#  CONFIGURATION & ARGUMENT PARSING
# =============================================================================
parser = argparse.ArgumentParser(description="Convert Deliverables (.docx) to Markdown for MCP.")
parser.add_argument('--path', required=True, help="Target deliverables root directory to scan.")
parser.add_argument('--directory-prefixes', default="", help="Comma-separated folder prefixes (e.g., DD130,D0180). Leave empty for all.")
parser.add_argument('--extensions', default=".docx,.xlsx,.pptx,.pdf,.csv,.tsv,.json,.html,.xml,.txt,.md,.rtf", help="Comma-separated file extensions to process.")
parser.add_argument('--outdir', required=True, help="Root output directory for the generated markdown files.")
args = parser.parse_args()

DELIVERABLES_DIRS = [args.path]
OUTPUT_DIR = args.outdir
SUPPORTED_EXTS = tuple(ext.strip().lower() for ext in args.extensions.split(',') if ext.strip())

# Parse directory_prefixes into a lowercase list. If empty, list remains empty.
if args.directory_prefixes.strip():
    TARGET_FOLDER_PREFIXES = [p.strip().lower() for p in args.directory_prefixes.split(',')]
else:
    TARGET_FOLDER_PREFIXES = []

CLEAN_MD = True
DRAFT_THRESHOLD = 2
SKIP_DEPRECATED = True
DRY_RUN = False
VERBOSE = True

# =============================================================================
#  COMPILED REGULAR EXPRESSIONS
# =============================================================================
_DATA_URI_RE = re.compile(r'!\[([^\]]*)\]\(data:([^;]+);base64,([^)]+)\)')

# Boilerplate Headers Regex (ignores spaces, markdown formatting chars like #, *, -, _)
_TOC_HEADER_RE = re.compile(r"^[\s#\*\-_]*(table\s+of\s+contents|indholdsfortegnelse|indhold)[\s\*\-_]*$", re.IGNORECASE)
_REF_HEADER_RE = re.compile(r"^[\s#\*\-_]*(references|referencer|litteraturliste)[\s\*\-_]*$", re.IGNORECASE)
_TOC_LINK_RE = re.compile(r"^\[.+\]\(#_Toc\w+\)\s*$")

# =============================================================================

@dataclasses.dataclass
class ConversionTask:
    src_path: str
    dest_path: str
    draft_dest_path: str

@dataclasses.dataclass
class ConversionResult:
    task: ConversionTask
    final_dest_path: str
    is_draft: bool
    no_status: int
    warnings: int
    error: str | None
    log_messages: list[str]

_written_this_session: dict[str, tuple[str, str, ConversionTask | None]] = {}

@dataclasses.dataclass
class Stats:
    converted: int = 0
    up_to_date: int = 0
    draft: int = 0
    no_status: int = 0
    errors: int = 0
    skipped: int = 0
    duplicates: int = 0
    warnings: int = 0
    orphans_removed: int = 0
    time_taken_seconds: float = 0.0

_md_instance = None
def _get_md() -> markitdown.MarkItDown:
    global _md_instance
    if _md_instance is None:
        _md_instance = markitdown.MarkItDown(enable_plugins=False)
    return _md_instance


def is_deprecated(path: str) -> bool:
    return "deprecated" in path.lower()


def clean_stem(stem: str, folder_name: str) -> str:
    stem = stem.replace("\u2013", "-").replace("\u2014", "-")
    stem = re.sub(r" {2,}", " ", stem).strip()
    return stem


def matches_target(folder_name: str) -> bool:
    if not TARGET_FOLDER_PREFIXES:
        return True
    return any(folder_name.lower().startswith(prefix) for prefix in TARGET_FOLDER_PREFIXES)


def slugify_folder(folder_name: str) -> str:
    slug = folder_name.replace(" - ", "-")
    slug = slug.replace(" ", "-")
    return slug


def strip_boilerplate(text: str, src_path: str = "") -> tuple[str, bool]:
    lines = text.splitlines(keepends=True)
    toc_header_idx = None

    # 1. Locate Table of Contents
    for i, line in enumerate(lines):
        if _TOC_HEADER_RE.match(line):
            toc_header_idx = i
            break

    if toc_header_idx is None:
        return text, False

    # 2. Find the end of the ToC links
    toc_end_idx = toc_header_idx
    for i in range(toc_header_idx + 1, len(lines)):
        stripped = lines[i].strip()
        if stripped == "" or _TOC_LINK_RE.match(stripped):
            toc_end_idx = i
        else:
            break

    # 3. Scan backwards from ToC to find References block
    references_start_idx = None
    for i in range(toc_header_idx - 1, -1, -1):
        if _REF_HEADER_RE.match(lines[i]):
            references_start_idx = i
            break

    references_block = ""
    has_refs = False
    if references_start_idx is not None:
        references_block = "".join(lines[references_start_idx:toc_header_idx]).strip("\n") + "\n\n"
        has_refs = True

    # 4. Construct final output
    rest = "".join(lines[toc_end_idx + 1:]).lstrip("\n")
    result = references_block + rest

    warned = False
    if not has_refs:
        label = src_path or "unknown file"
        print(f"  WARNING: references section missing from output: {label}")
        warned = True

    return result, warned


def fix_table_empty_header_rows(text: str) -> str:
    sep_pattern = re.compile(r"^\|[\s\-|]+\|$")
    lines = text.splitlines(keepends=True)
    result = []
    i = 0
    while i < len(lines):
        current = lines[i].rstrip("\n")
        next_line = lines[i + 1].rstrip("\n") if i + 1 < len(lines) else ""
        if (current.startswith("|") and current.endswith("|") and sep_pattern.match(next_line)):
            cells = current.split("|")[1:-1]
            if all(c.strip() == "" for c in cells):
                after_sep = lines[i + 2].rstrip("\n") if i + 2 < len(lines) else ""
                if after_sep.startswith("|") and after_sep.endswith("|"):
                    result.append(lines[i + 2])
                    result.append(lines[i + 1])
                    i += 3
                    continue
        result.append(lines[i])
        i += 1
    return "".join(result)


def extract_images(src_docx: str, content: str, images_dir: str, doc_stem: str) -> tuple[str, int]:
    zip_media_hashes = {}

    with zipfile.ZipFile(src_docx, "r") as z:
        for item in z.namelist():
            if item.startswith("word/media/"):
                binary = z.read(item)
                h = hashlib.md5(binary).hexdigest()
                zip_media_hashes[h] = (item, binary)

    warnings = 0

    def replace_base64(m: re.Match) -> str:
        nonlocal warnings
        alt_text, mime_type, b64_data = m.group(1), m.group(2), m.group(3)

        try:
            decoded_img = base64.b64decode(b64_data)
            img_hash = hashlib.md5(decoded_img).hexdigest()

            if img_hash in zip_media_hashes:
                orig_path, binary = zip_media_hashes[img_hash]
                filename = os.path.basename(orig_path)
            else:
                ext = mimetypes.guess_extension(mime_type) or ".bin"
                if ext == ".jpe":
                    ext = ".jpg"
                filename = f"extracted_{img_hash[:8]}{ext}"
                binary = decoded_img

            dest_name = f"{doc_stem}-{filename}"
            dest_file = os.path.join(images_dir, dest_name)

            if not DRY_RUN:
                os.makedirs(images_dir, exist_ok=True)
                with open(dest_file, "wb") as dst:
                    dst.write(binary)

            return f"![{alt_text}](./.attachments/{dest_name})"

        except Exception:
            warnings += 1
            return m.group(0)

    updated_content = _DATA_URI_RE.sub(replace_base64, content)
    return updated_content, warnings


def execute_conversion(task: ConversionTask) -> ConversionResult:
    logs = []
    warnings_count = 0
    no_status_count = 0
    is_draft = False
    final_dest_path = task.dest_path

    try:
        if os.path.exists(task.draft_dest_path) and not DRY_RUN:
            try:
                os.remove(task.draft_dest_path)
            except OSError:
                pass

        md = _get_md()
        result = md.convert(task.src_path)
        content = result.text_content

        match = re.search(r'\|\s*\*\*Status\*\*\s*\|\s*(.+?)\s*\|', content)
        if match:
            try:
                status_val = int(match.group(1).strip().split('-')[0].strip())
                is_draft = status_val <= DRAFT_THRESHOLD
            except ValueError:
                logs.append(f"  WARNING: unreadable status value in {task.src_path}")
                warnings_count += 1
                no_status_count += 1
        else:
            logs.append(f"  WARNING: no status field found in {task.src_path}")
            warnings_count += 1
            no_status_count += 1

        is_docx = task.src_path.lower().endswith(".docx")
        if is_docx and CLEAN_MD:
            content, bp_warned = strip_boilerplate(content, task.src_path)
            if bp_warned:
                warnings_count += 1
            content = fix_table_empty_header_rows(content)

        dest_dir = os.path.dirname(task.dest_path)
        doc_stem = os.path.splitext(os.path.basename(task.dest_path))[0]
        images_dir = os.path.join(dest_dir, ".attachments")

        if is_docx:
            content, img_warnings = extract_images(task.src_path, content, images_dir, doc_stem)
            warnings_count += img_warnings

        if DRY_RUN:
            logs.append(f"  [DRY RUN] Would write: {task.dest_path}")
        else:
            os.makedirs(dest_dir, exist_ok=True)
            with open(task.dest_path, "w", encoding="utf-8") as f:
                f.write(content)
            if VERBOSE:
                logs.append(f"  Converted: {task.src_path}\n         -> {task.dest_path}")

        if is_draft:
            new_dest_filename = f"draft-{os.path.basename(task.dest_path)}"
            new_dest_path = os.path.join(dest_dir, new_dest_filename)

            if not DRY_RUN and os.path.exists(new_dest_path):
                try: os.remove(new_dest_path)
                except OSError: pass

            if DRY_RUN:
                final_dest_path = new_dest_path
                logs.append(f"  [DRY RUN] Would mark as draft: {new_dest_filename}")
            else:
                try:
                    os.rename(task.dest_path, new_dest_path)
                    final_dest_path = new_dest_path
                    if VERBOSE:
                        logs.append(f"  Marked as draft: {new_dest_filename}")
                except OSError as rename_err:
                    logs.append(f"  WARNING: could not rename file to include status: {rename_err}")
                    warnings_count += 1

        return ConversionResult(task, final_dest_path, is_draft, no_status_count, warnings_count, None, logs)

    except Exception as e:
        return ConversionResult(task, final_dest_path, False, 0, 0, str(e), logs)


def short_name(deliverables_dir: str) -> str:
    name = os.path.basename(deliverables_dir)
    lower = name.lower()
    if lower.startswith("deliverables-"): return name[len("deliverables-"):]
    if lower.startswith("deliverables"):  return name[len("deliverables"):]
    return name


def get_discriminator(src_path: str, deliverables_dir: str) -> str:
    norm_src = os.path.normpath(src_path)
    norm_root = os.path.normpath(deliverables_dir)
    rel = os.path.relpath(norm_src, norm_root)
    parts = rel.split(os.sep)
    if len(parts) >= 2: return parts[0]
    return ""


def is_generic_stem(stem: str, folder_name: str) -> bool:
    if not stem.strip(): return True
    clean_folder = folder_name.replace("\u2013", "-").replace("\u2014", "-")
    segments = clean_folder.split(" - ")
    descriptive = " - ".join(segments[1:]) if len(segments) > 1 else ""
    return stem.strip().lower() == descriptive.strip().lower()


def _apply_discriminator_prefix(dest_path: str, discriminator: str) -> str:
    dest_dir = os.path.dirname(dest_path)
    dest_file = os.path.basename(dest_path)
    return os.path.join(dest_dir, f"{discriminator} - {dest_file}")


def process_directory(deliverables_dir: str, stats: Stats, tasks: list[ConversionTask]) -> None:
    root_name = short_name(deliverables_dir)

    for root, dirs, files in os.walk(deliverables_dir):
        current_folder = os.path.basename(root)
        if not matches_target(current_folder): continue

        for filename in files:
            if not filename.lower().endswith(SUPPORTED_EXTS): continue

            src_path = os.path.join(root, filename)

            if SKIP_DEPRECATED and is_deprecated(src_path):
                if VERBOSE: print(f"  Skipping deprecated: {src_path}")
                stats.skipped += 1
                continue

            stem = clean_stem(os.path.splitext(filename)[0], current_folder)
            if is_generic_stem(stem, current_folder):
                discriminator = get_discriminator(src_path, deliverables_dir)
                if discriminator:
                    stem = f"{discriminator} {stem}" if stem.strip() else discriminator
                    if VERBOSE: print(f"  Generic stem: prepending discriminator -> '{stem}'")

            dest_filename_base = f"{stem}.md"
            folder_slug = slugify_folder(current_folder)
            dest_path = os.path.join(OUTPUT_DIR, root_name, folder_slug, dest_filename_base)

            dest_key = os.path.normcase(dest_path)
            if dest_key in _written_this_session:
                discriminator = get_discriminator(src_path, deliverables_dir)
                orig_dest_path, orig_discriminator, orig_task = _written_this_session[dest_key]
                stats.duplicates += 1

                if discriminator and orig_discriminator:
                    renamed_orig = _apply_discriminator_prefix(orig_dest_path, orig_discriminator)

                    if orig_task:
                        orig_task.dest_path = renamed_orig
                        orig_task.draft_dest_path = os.path.join(os.path.dirname(renamed_orig), f"draft-{os.path.basename(renamed_orig)}")
                        if VERBOSE: print(f"  Duplicate resolved: updated queued task -> {renamed_orig}")
                    else:
                        if not DRY_RUN:
                            try:
                                if os.path.exists(orig_dest_path): os.rename(orig_dest_path, renamed_orig)
                                if VERBOSE: print(f"  Duplicate resolved: renamed existing -> {renamed_orig}")
                            except OSError as rename_err:
                                print(f"  ERROR duplicate: could not rename {orig_dest_path}: {rename_err}")
                        elif VERBOSE:
                            print(f"  [DRY RUN] Would rename existing -> {renamed_orig}")

                    del _written_this_session[dest_key]
                    _written_this_session[os.path.normcase(renamed_orig)] = (renamed_orig, orig_discriminator, orig_task)

                    dest_path = _apply_discriminator_prefix(dest_path, discriminator)
                    dest_key = os.path.normcase(dest_path)
                    if VERBOSE: print(f"  Duplicate resolved: new file -> {dest_path}")
                else:
                    dest_base, dest_ext = os.path.splitext(dest_path)
                    counter = 2
                    while os.path.normcase(f"{dest_base}-{counter}{dest_ext}") in _written_this_session:
                        counter += 1
                    dest_path = f"{dest_base}-{counter}{dest_ext}"
                    dest_key = os.path.normcase(dest_path)
                    if VERBOSE: print(f"  Duplicate resolved (counter): {dest_path}")

            dest_dir = os.path.dirname(dest_path)
            dest_file = os.path.basename(dest_path)
            draft_dest_path = os.path.join(dest_dir, f"draft-{dest_file}")

            existing_path = None
            if os.path.exists(dest_path): existing_path = dest_path
            elif os.path.exists(draft_dest_path): existing_path = draft_dest_path

            if existing_path and os.path.getmtime(existing_path) >= os.path.getmtime(src_path):
                if VERBOSE: print(f"  [SKIPPED - up to date]: {existing_path}")
                stats.up_to_date += 1
                dest_key = os.path.normcase(existing_path)
                _written_this_session[dest_key] = (existing_path, get_discriminator(src_path, deliverables_dir), None)
                continue

            task = ConversionTask(src_path, dest_path, draft_dest_path)
            tasks.append(task)
            _written_this_session[dest_key] = (dest_path, get_discriminator(src_path, deliverables_dir), task)


def _print_summary(stats: Stats) -> None:
    total = stats.converted + stats.errors + stats.up_to_date
    rows = [
        ("Documents found",        total),
        ("Converted successfully", stats.converted),
        ("Skipped (up to date)",   stats.up_to_date),
        ("  of which draft",       stats.draft),
        ("  of which no status",   stats.no_status),
        ("Errors",                 stats.errors),
        ("Skipped (deprecated)",   stats.skipped),
        ("Duplicate paths resolved", stats.duplicates),
        ("Orphans removed",        stats.orphans_removed),
        ("Warnings",               stats.warnings),
    ]
    label_w = max(len(r[0]) for r in rows)
    sep = "+" + "-" * (label_w + 2) + "+" + "-" * 8 + "+"
    print(f"\n{sep}")
    print(f"| {'Run summary':<{label_w}} | {'Count':>6} |")
    print(sep)
    for label, count in rows:
        print(f"| {label:<{label_w}} | {count:>6} |")
    print(sep)
    print(f"Total time taken: {stats.time_taken_seconds:.2f} seconds")


def main() -> None:
    start_time = time.time()
    stats = Stats()
    tasks: list[ConversionTask] = []

    for deliverables_dir in DELIVERABLES_DIRS:
        if not os.path.isdir(deliverables_dir):
            print(f"WARNING: Deliverables directory not found, skipping: {deliverables_dir}")
            stats.warnings += 1
            continue
        if VERBOSE: print(f"\nScanning Phase: {deliverables_dir}")
        process_directory(deliverables_dir, stats, tasks)

    if tasks:
        print(f"\nExecution Phase: Converting {len(tasks)} items concurrently...")
        with concurrent.futures.ProcessPoolExecutor() as executor:
            futures = {executor.submit(execute_conversion, task): task for task in tasks}
            for future in concurrent.futures.as_completed(futures):
                res = future.result()

                if VERBOSE:
                    for log in res.log_messages: print(log)

                if res.error:
                    print(f"  ERROR converting {res.task.src_path}: {res.error}")
                    stats.errors += 1
                else:
                    stats.converted += 1
                    stats.warnings += res.warnings
                    stats.no_status += res.no_status
                    if res.is_draft: stats.draft += 1

                    orig_key = os.path.normcase(res.task.dest_path)
                    if orig_key in _written_this_session:
                        disc = _written_this_session[orig_key][1]
                        del _written_this_session[orig_key]
                        _written_this_session[os.path.normcase(res.final_dest_path)] = (res.final_dest_path, disc, None)

    if not DRY_RUN and os.path.exists(OUTPUT_DIR):
        valid_paths = {os.path.abspath(info[0]) for info in _written_this_session.values()}
        for root, dirs, files in os.walk(OUTPUT_DIR):
            for file in files:
                if file.endswith(".md"):
                    full_path = os.path.join(root, file)
                    if os.path.abspath(full_path) not in valid_paths:
                        try:
                            os.remove(full_path)
                            stats.orphans_removed += 1
                            if VERBOSE: print(f"  [CLEANUP] Removed orphaned file: {full_path}")
                        except OSError as e:
                            print(f"  WARNING: failed to remove orphaned file {full_path}: {e}")

    stats.time_taken_seconds = time.time() - start_time
    _print_summary(stats)
    manifest_data = {
        "converted": stats.converted,
        "orphans_removed": stats.orphans_removed,
        "total_modifications": stats.converted + stats.orphans_removed,
        "errors": stats.errors,
        "warnings": stats.warnings
    }
    manifest_path = os.path.join(OUTPUT_DIR, "manifest.json")
    if not DRY_RUN:
        os.makedirs(OUTPUT_DIR, exist_ok=True)
        with open(manifest_path, "w", encoding="utf-8") as f:
            json.dump(manifest_data, f, indent=4)

if __name__ == "__main__":
    main()
